export const BANNERS = {
  onePepeBanner: [
    {
      name: "Roronoa Pepe",
      rarity: "PepeLendaPlusPlus",
      type: "Personagem",
      eventName: "One Pepe",
      pullTime: "",
    },
    {
      name: "Pepe Brook",
      rarity: "PepeRaroPlusPlus",
      type: "Personagem",
      eventName: "One Pepe",
      pullTime: "",
    },
    {
      name: "Smoker Pepe",
      rarity: "PepeRaroPlusPlus",
      type: "Personagem",
      eventName: "One Pepe",
      pullTime: "",
    },
    {
      name: "Choppepe",
      rarity: "PepeRaroPlusPlus",
      type: "Personagem",
      eventName: "One Pepe",
      pullTime: "",
    },
    {
      name: "Espada de Madeira",
      rarity: "PepeRaro",
      type: "Arma",
      eventName: "One Pepe",
      pullTime: "",
    },
    {
      name: "Estilingue Absurdo",
      rarity: "PepeRaro",
      type: "Arma",
      eventName: "One Pepe",
      pullTime: "",
    },
    {
      name: "Bastão Climático",
      rarity: "PepeRaro",
      type: "Arma",
      eventName: "One Pepe",
      pullTime: "",
    },
    {
      name: "Bota de Combate",
      rarity: "PepeRaro",
      type: "Arma",
      eventName: "One Pepe",
      pullTime: "",
    },
    {
      name: "Cano de Encanador",
      rarity: "PepeRaro",
      type: "Arma",
      eventName: "One Pepe",
      pullTime: "",
    },
  ],
  pepeKatsukiBanner: [
    {
      name: "Pepe Filler Lenda",
      rarity: "PepeLendaPlusPlus",
      type: "Personagem",
      eventName: "PepeKatsuki",
      pullTime: "",
    },
    {
      name: "Pepe Filler",
      rarity: "PepeRaroPlusPlus",
      type: "Personagem",
      eventName: "PepeKatsuki",
      pullTime: "",
    },
    {
      name: "Pepe Itachi",
      rarity: "PepeRaroPlusPlus",
      type: "Personagem",
      eventName: "PepeKatsuki",
      pullTime: "",
    },
    {
      name: "Pepe Deidara",
      rarity: "PepeRaroPlusPlus",
      type: "Personagem",
      eventName: "PepeKatsuki",
      pullTime: "",
    },
    {
      name: "Espada de Madeira",
      rarity: "PepeRaro",
      type: "Arma",
      eventName: "PepeKatsuki",
      pullTime: "",
    },
    {
      name: "Estilingue Absurdo",
      rarity: "PepeRaro",
      type: "Arma",
      eventName: "PepeKatsuki",
      pullTime: "",
    },
    {
      name: "Bastão Climático",
      rarity: "PepeRaro",
      type: "Arma",
      eventName: "PepeKatsuki",
      pullTime: "",
    },
    {
      name: "Bota de Combate",
      rarity: "PepeRaro",
      type: "Arma",
      eventName: "PepeKatsuki",
      pullTime: "",
    },
    {
      name: "Cano de Encanador",
      rarity: "PepeRaro",
      type: "Arma",
      eventName: "PepeKatsuki",
      pullTime: "",
    },
  ],
};
